name: Manual Deployment to Staging

on:
  workflow_dispatch:
    # see promote-prod for notes
    inputs:
      deploy-app:
        description: "Deploy front end"
        required: false
        type: boolean
      deploy-server:
        description: "Deploy IAM server"
        required: false
        type: boolean
      commit:
        description: "Commit ref"
        required: true
        type: string

jobs:
  deploy-app:
    if: github.event.inputs.deploy-app == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # push commit hash to fleek api -- staging

  deploy-server:
    if: github.event.inputs.deploy-server == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # deploy image to appropriate cluster -- staging
