name: Release and Deploy

on:
  workflow_call:
    inputs:
      refspec:
        required: true
        type: string
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      staging_frontend_branch:
        required: true
        type: string
      production_frontend_branch:
        required: true
        type: string
      staging_domain:
        required: true
        type: string
      production_domain:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string

jobs:
  test:
    name: Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          ref: ${{ inputs.refspec }}
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: "yarn"

      - name: Install Packages
        run: yarn install

      - name: Run Tests
        run: |
          yarn test

      - name: Run Linter
        run: |
          yarn lint

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"

      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.github_token }}
          tag: ${{ steps.version.outputs.version_tag }}
          commit: ${{ inputs.refspec }}
          draft: true

      - name: Store Commit SHA
        id: sha
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short ${{ inputs.refspec }})" >> $GITHUB_OUTPUT

    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}
      commit_sha: ${{ steps.sha.outputs.sha_short }}

  dockerize:
    name: Dockerize
    needs: [test]
    uses: gitcoinco/passport/.github/workflows/dockerize.yml@main
    with:
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ needs.test.outputs.commit_sha }}
      ecr_repository: ${{ inputs.ecr_repository }}
    secrets: inherit

  preview_staging_backend:
    name: Preview Pulumi changes for Staging Backend - AWS Infra
    needs: [test, dockerize]
    uses: gitcoinco/passport/.github/workflows/deploy_to_aws.yml@main
    with:
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ needs.test.outputs.commit_sha }}
      domain: ${{ inputs.staging_domain }}
      stack_name: gitcoin/staging
      pulumi_working_dir: infra/aws
      pulumi_region: us-west-2
      pulumi_cmd: preview

      staking_app_github_url: ${{ vars.STAKING_APP_GITHUB_URL_STAGING }}
      staking_app_enable_auth: ${{ vars.STAKING_APP_ENABLE_AUTH_STAGING }}
      staking_app_basic_auth_username: ${{ vars.STAKING_APP_BASIC_AUTH_USERNAME_STAGING }}

    
    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      ECR_URL: ${{secrets.ECR_URL_STAGING}}
      ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID_STAGING }}
      IAM_SERVER_SSM_ARN: ${{ secrets.IAM_SERVER_SSM_ARN_STAGING }}
      PAGERDUTY_INTEGRATION_ENDPOINT: ${{ secrets.PAGERDUTY_INTEGRATION_ENDPOINT }}
      PASSPORT_VC_SECRETS_ARN: ${{ secrets.PASSPORT_VC_SECRETS_ARN_STAGING }}

      STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY: ${{ secrets.STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY_STAGING }}
      STAKING_APP_BASIC_AUTH_PASSWORD: ${{ secrets.STAKING_APP_BASIC_AUTH_PASSWORD_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_STAGING: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION }}
      STAKING_MAINNET_RPC_URL: ${{ secrets.STAKING_MAINNET_RPC_URL }}
      STAKING_OP_SEPOLIA_RPC_URL: ${{ secrets.STAKING_OP_SEPOLIA_RPC_URL }}
      STAKING_OP_RPC_URL: ${{ secrets.STAKING_OP_RPC_URL }}

      STAKING_WALLET_CONNECT_PROJECT_ID: ${{ secrets.STAKING_WALLET_CONNECT_PROJECT_ID_STAGING }}
      STAKING_INTERCOM_APP_ID: ${{ secrets.STAKING_APP_INTERCOM_APP_ID_STAGING }}
      STAKING_ARBITRUM_RPC_URL: ${{ secrets.STAKING_ARBITRUM_RPC_URL }}

      # cloudflare config : just for production
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  wait_for_staging_approval:
    name: Staging Approval Pending
    needs: [test, dockerize, preview_staging_backend]
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Approve Release to Staging (check pulumi preview)
        run: |
          echo "Approved Staging Release for: " ${{ needs.test.outputs.version_tag }}
          echo "Ref" ${{ inputs.refspec }}
  
  deploy_staging_frontend:
    name: Staging Frontend
    permissions: write-all
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval]
    uses: gitcoinco/passport/.github/workflows/deploy_to_branch.yml@main
    with:
      owner: ${{ inputs.repo_owner }}
      repo: ${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      destination_branch: ${{ inputs.staging_frontend_branch }}

  deploy_staging_backend:
    name: Staging Backend
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval]
    uses: gitcoinco/passport/.github/workflows/deploy_to_aws.yml@main
    with:
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ needs.test.outputs.commit_sha }}
      domain: ${{ inputs.staging_domain }}
      stack_name: gitcoin/staging
      pulumi_working_dir: infra/aws
      pulumi_region: us-west-2
      pulumi_cmd: up

      staking_app_github_url: ${{ vars.STAKING_APP_GITHUB_URL_STAGING }}
      staking_app_enable_auth: ${{ vars.STAKING_APP_ENABLE_AUTH_STAGING }}
      staking_app_basic_auth_username: ${{ vars.STAKING_APP_BASIC_AUTH_USERNAME_STAGING }}

    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      ECR_URL: ${{secrets.ECR_URL_STAGING}}
      ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID_STAGING }}
      IAM_SERVER_SSM_ARN: ${{ secrets.IAM_SERVER_SSM_ARN_STAGING }}
      PAGERDUTY_INTEGRATION_ENDPOINT: ${{ secrets.PAGERDUTY_INTEGRATION_ENDPOINT }}
      PASSPORT_VC_SECRETS_ARN: ${{ secrets.PASSPORT_VC_SECRETS_ARN_STAGING }}

      STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY: ${{ secrets.STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY_STAGING }}
      STAKING_APP_BASIC_AUTH_PASSWORD: ${{ secrets.STAKING_APP_BASIC_AUTH_PASSWORD_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_STAGING: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION }}
      STAKING_MAINNET_RPC_URL: ${{ secrets.STAKING_MAINNET_RPC_URL }}
      STAKING_OP_SEPOLIA_RPC_URL: ${{ secrets.STAKING_OP_SEPOLIA_RPC_URL }}
      STAKING_OP_RPC_URL: ${{ secrets.STAKING_OP_RPC_URL }}

      STAKING_WALLET_CONNECT_PROJECT_ID: ${{ secrets.STAKING_WALLET_CONNECT_PROJECT_ID_STAGING }}
      STAKING_INTERCOM_APP_ID: ${{ secrets.STAKING_APP_INTERCOM_APP_ID_STAGING }}
      STAKING_ARBITRUM_RPC_URL: ${{ secrets.STAKING_ARBITRUM_RPC_URL }}

      # cloudflare config : just for production
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  preview_production_backend:
    name: Preview Pulumi changes for Production Backend - AWS Infra
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval, deploy_staging_frontend, deploy_staging_backend]
    uses: gitcoinco/passport/.github/workflows/deploy_to_aws.yml@main
    with:
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ needs.test.outputs.commit_sha }}
      domain: passport-iam.gitcoin.co
      stack_name: gitcoin/production
      pulumi_working_dir: infra/aws
      pulumi_region: us-west-2
      pulumi_cmd: preview

      staking_app_github_url: ${{ vars.STAKING_APP_GITHUB_URL_PRODUCTION }}
      staking_app_enable_auth: ${{ vars.STAKING_APP_ENABLE_AUTH_PRODUCTION }}
      staking_app_basic_auth_username: ${{ vars.STAKING_APP_BASIC_AUTH_USERNAME_PRODUCTION }}

    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      ECR_URL: ${{secrets.AWS_ECR_URL_PRODUCTION}}
      ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID_PRODUCTION }}
      IAM_SERVER_SSM_ARN: ${{ secrets.AWS_IAM_SERVER_SSM_ARN_PRODUCTION }}
      PAGERDUTY_INTEGRATION_ENDPOINT: ${{ secrets.PAGERDUTY_INTEGRATION_ENDPOINT }}
      PASSPORT_VC_SECRETS_ARN: ${{ secrets.AWS_PASSPORT_VC_SECRETS_ARN_PRODUCTION }}

      STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY: ${{ secrets.STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY_PRODUCTION }}
      STAKING_APP_BASIC_AUTH_PASSWORD: ${{ secrets.STAKING_APP_BASIC_AUTH_PASSWORD_PRODUCTION }}
      STAKING_DATADOG_CLIENT_TOKEN_STAGING: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION }}
      STAKING_MAINNET_RPC_URL: ${{ secrets.STAKING_MAINNET_RPC_URL }}
      STAKING_OP_SEPOLIA_RPC_URL: ${{ secrets.STAKING_OP_SEPOLIA_RPC_URL }}
      STAKING_OP_RPC_URL: ${{ secrets.STAKING_OP_RPC_URL }}

      STAKING_WALLET_CONNECT_PROJECT_ID: ${{ secrets.STAKING_WALLET_CONNECT_PROJECT_ID_PRODUCTION }}
      STAKING_INTERCOM_APP_ID: ${{ secrets.STAKING_APP_INTERCOM_APP_ID_PRODUCTION }}
      STAKING_ARBITRUM_RPC_URL: ${{ secrets.STAKING_ARBITRUM_RPC_URL }}

      # cloudflare config : just for production
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  
  wait_for_production_approval:
    name: Production Approval Pending
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval, deploy_staging_frontend, deploy_staging_backend,  preview_production_backend]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Approve Release to Production
        run: |
          echo "Approved Production Release for: " ${{ needs.test.outputs.version_tag }}
          echo "Ref" ${{ inputs.refspec }}

  deploy_production_frontend:
    name: Production Frontend
    permissions: write-all
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval, deploy_staging_frontend, deploy_staging_backend,  preview_production_backend, wait_for_production_approval]
    uses: gitcoinco/passport/.github/workflows/deploy_to_branch.yml@main
    with:
      owner: ${{ inputs.repo_owner }}
      repo: ${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      destination_branch: ${{ inputs.production_frontend_branch }}

  deploy_production_backend:
    name: Production Backend - AWS Infra
    needs: [test, dockerize, preview_staging_backend, wait_for_staging_approval, deploy_staging_frontend, deploy_staging_backend, preview_production_backend, wait_for_production_approval]
    uses: gitcoinco/passport/.github/workflows/deploy_to_aws.yml@main
    with:
      repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
      refspec: ${{ inputs.refspec }}
      docker_tag: ${{ needs.test.outputs.commit_sha }}
      domain: passport-iam.gitcoin.co
      stack_name: gitcoin/production
      pulumi_working_dir: infra/aws
      pulumi_region: us-west-2
      pulumi_cmd: up

      staking_app_github_url: ${{ vars.STAKING_APP_GITHUB_URL_PRODUCTION }}
      staking_app_enable_auth: ${{ vars.STAKING_APP_ENABLE_AUTH_PRODUCTION }}
      staking_app_basic_auth_username: ${{ vars.STAKING_APP_BASIC_AUTH_USERNAME_PRODUCTION }}

    secrets:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
      ECR_URL: ${{secrets.AWS_ECR_URL_PRODUCTION}}
      ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID_PRODUCTION }}
      IAM_SERVER_SSM_ARN: ${{ secrets.AWS_IAM_SERVER_SSM_ARN_PRODUCTION }}
      PAGERDUTY_INTEGRATION_ENDPOINT: ${{ secrets.PAGERDUTY_INTEGRATION_ENDPOINT }}
      PASSPORT_VC_SECRETS_ARN: ${{ secrets.AWS_PASSPORT_VC_SECRETS_ARN_PRODUCTION }}

      STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY: ${{ secrets.STAKING_APP_GITHUB_ACCESS_TOKEN_FOR_AMPLIFY_PRODUCTION }}
      STAKING_APP_BASIC_AUTH_PASSWORD: ${{ secrets.STAKING_APP_BASIC_AUTH_PASSWORD_PRODUCTION }}
      STAKING_DATADOG_CLIENT_TOKEN_STAGING: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_STAGING }}
      STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION: ${{ secrets.STAKING_DATADOG_CLIENT_TOKEN_PRODUCTION }}
      STAKING_MAINNET_RPC_URL: ${{ secrets.STAKING_MAINNET_RPC_URL }}
      STAKING_OP_SEPOLIA_RPC_URL: ${{ secrets.STAKING_OP_SEPOLIA_RPC_URL }}
      STAKING_OP_RPC_URL: ${{ secrets.STAKING_OP_RPC_URL }}

      STAKING_WALLET_CONNECT_PROJECT_ID: ${{ secrets.STAKING_WALLET_CONNECT_PROJECT_ID_PRODUCTION }}
      STAKING_INTERCOM_APP_ID: ${{ secrets.STAKING_APP_INTERCOM_APP_ID_PRODUCTION }}
      STAKING_ARBITRUM_RPC_URL: ${{ secrets.STAKING_ARBITRUM_RPC_URL }}

      # cloudflare config : just for production
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  
  release:
    needs: [deploy_production_backend, deploy_production_frontend, test]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          ref: ${{ inputs.refspec }}
          fetch-depth: 0

      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          omitBodyDuringUpdate: true
          allowUpdates: true
          token: ${{ secrets.github_token }}
          tag: ${{ needs.test.outputs.version_tag }}
          commit: ${{ inputs.refspec }}
          draft: false
